<?php
/**
 * Created by PhpStorm.
 * User: chenweihua
 * Date: 2019/10/30
 * Time: 12:53 AM
 */

namespace app\admin\controller;


use think\Controller;
use think\Db;

class Admin extends BaseController
{
    public function initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch();
    }

    public function lists(){
        $lists = Db::name('admin_user')->paginate(15)->toArray();
        $this->assign('lists',$lists);
        return $this->listsData($lists['data'],$lists['total']);
    }

    public function create()
    {
        $result = Db::name('auth_group')->select();
        $this->assign('result',$result);
        if (request()->isPost()) {
            $data = [
                'admin_name' => input('username'),
                'password' => md5(input('password')),
            ];
            if (Db::name('admin_user')->where('admin_name',$data['admin_name'])->find()){
                return $this->error('用户名已经存在','index');
            }else{
                $obj = input('interest');
                if (Db::name('admin_user')->insert($data)) {
                    $username = $data['admin_name'];
                    $obj1 = Db::name('admin_user')->where('admin_name',$username)->find();
                    $data1 = [
                        'uid' => $obj1['id'],
                        'group_id' => $obj,
                    ];
                    if (Db::name('auth_group_access')->insert($data1)){
                        return $this->success('success!', 'index');
                    }
                } else {
                    return $this->error('error!', 'index');
                }
            }
        }
        return $this->fetch();
    }

    public function edit()
    {
        $id = input('id');
        $admin = Db::name('admin_user')->where('id',$id)->find();
        $this->assign('admin',$admin);
        if (request()->isPost()){
            $data = [
                'id' => $id,
                'admin_name' => input('admin_name'),
                'password' => md5(input('password')),
            ];
            if (Db::name('admin_user')->where('id',$id)->update($data)){
                return $this->success('success!','index');
            }else{
                return $this->error('error!','index');
            }
        }
        return $this->fetch();
    }

    public function del()
    {
        $id = input('id');
        Db::name('admin_user')->where('id',$id)->delete();
    }
}