<?php
/**
 * Created by PhpStorm.
 * User: chenweihua
 * Date: 2019/11/13
 * Time: 4:40 PM
 */

namespace app\admin\controller;


class Welcome extends BaseController
{
    public function _initialize()
    {
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function welcome()
    {
        return $this->fetch();
    }
}