<?php
/**
 * Created by PhpStorm.
 * User: chenweihua
 * Date: 2019/11/21
 * Time: 2:03 PM
 */

namespace app\index\controller;

use Predis\Client;

use think\cache\driver\Redis;
use think\Db;
use think\facade\Cache;


class Detail extends BaseController
{
    private $product_id = [1,2];

    public function initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
        //秒杀抢购
//    public function add()
//    {
//        $server = array(
//            'host' => '127.0.0.1',//IP
//            'port' => 6379,         //端口
//        );
//        $redis = new Client($server);
//        $seckillProduct = Db::name('product')->where('id','in',$this->product_id)->select();
//        foreach ($seckillProduct as $key=>$value){
//            $store = $value['amount']; //商品库存
//            for ($i=1;$i<=$store;$i++){
//                $redis->lPush('sellkillGoodId:'.$value['id'],$i);
//            }
//            echo '商品'.$value['product_name'].'添加成功';
//        }
//        return '添加成功';
//    }

    public function addCart()
    {
        Db::name('shop_cart')->where('buynow=1')->delete();
        if (request()->isPost()){
            $product_id = input('id');
            $price['price'] = Db::name('product')->where('id',$product_id)->find();
            $product = [
                'uid' => '3',
                'product_id' => $product_id,
                'number' => '1',
                'status' => '1',
                'buynow' => '0',
                'create_time' => time(),
                'price' => $price['price'],
            ];
            if (Db::name('shop_cart')->insert($product)){
                $response = array(
                    'errno' => '1',
                    'errmsg' => "success",
                    'data' => true,
                );
                return json_encode($response);
            }else{
                $response = array(
                    'errno' => '-1',
                    'errmsg' => "fail",
                    'data' => false,
                );
                return json_encode($response);
            }
        }
    }

    public function detail()
    {
//        $server = array(
//            'host' => '127.0.0.1',//IP
//            'port' => 6379,         //端口
//        );
//        $redis = new Client($server);
//        $product_id = input('id');
//        if (json_decode($redis->get('data'))){
//            echo 1;
//            $this->assign('data',$redis->get('data'));
//        }else{
//            echo 2;
//            $data = Db::name('product')->where('id',$product_id)->find();
//            Db::name('product')->where('id','=',$product_id)->setInc('click','1');
//            $this->assign('data',$data);
//            $data1 = json_encode($data);
//            $redis->set('data',$data);
//        }
        $product_id = input('id');
        $data = Db::name('product')->where('id',$product_id)->find();
        Db::name('product')->where('id','=',$product_id)->setInc('click','1');
        $this->assign('data',$data);
        return $this->fetch();
    }

    public function index()
    {
        $arr = [
            'id' => '1',
            'product_name' => '商品名称'
        ];

        foreach ($arr as $key=>$val) {
            var_dump($key);
            var_dump($val);
        }
        echo "<br>";
        $arr = [
            [
                'id' => '1',
                'product_name' => '商品名称'
            ]
        ];

        foreach ($arr as $key=>$val) {
            var_dump($key);
            var_dump($val);
        }
    }
}