<?php
/**
 * Created by PhpStorm.
 * User: chenweihua
 * Date: 2019/11/21
 * Time: 2:03 PM
 */

namespace app\index\controller;


use think\Controller;
use think\Db;

class Detail extends BaseController
{
    public function initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function addCart()
    {
        if (request()->isPost()){
            $productId = input('productId');
            $product = [
                'uid' => '1',
                'product_id' => $productId,
                'number' => '1',
                'status' => '1',
                'create_time' => time(),
            ];
            if (Db::name('shop_cart')->insert($product)){
//                echo 1;exit;
                $response = array(
                    'errno' => '1',
                    'errmsg' => "success",
                    'data' => true,
                );
                return json_encode($response);
            }else{
                $response = array(
                    'errno' => '-1',
                    'errmsg' => "fail",
                    'data' => false,
                );
                return json_encode($response);
            }
        }
    }

    public function detail()
    {
        $id = input('id');
        $data = Db::name('product')->where('id',$id)->find();
//        dump($data['color_id']);exit;
//        $color = Db::name('colors')->where('id',$data['color_id']->find());

//        $this->assign('color',$color);
        $this->assign('data',$data);
        return $this->fetch();
    }

    public function index()
    {
        $arr = [
            'id' => '1',
            'product_name' => '商品名称'
        ];

        foreach ($arr as $key=>$val) {
            var_dump($key);
            var_dump($val);
        }
        echo "<br>";
        $arr = [
            [
                'id' => '1',
                'product_name' => '商品名称'
            ]
        ];

        foreach ($arr as $key=>$val) {
            var_dump($key);
            var_dump($val);
        }
    }
}