<?php
namespace app\index\controller;

use think\Cache;
use think\Controller;
use think\Db;

class Index extends BaseController
{

    public function initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        //无限分类前台展示
//        $cate1 = Db::name('cate')->where('pid=0')->select();
//        foreach ($cate1 as $key=>$value){
//            $cate1[$key]['child'] = array();
//            $cate2 = Db::name('cate')->where('pid='.$value['id'])->select();
//            foreach ($cate2 as $k=>$v){
//                array_push($cate1[$key]['child'],$v);
//                $cate1[$key]['child'][$k]['child2'] = array();
//                $cate3 = Db::name('cate')->where('pid='.$v['id'])->select();
//                foreach ($cate3 as $v2){
//                    array_push($cate1[$key]['child'][$k]['child2'],$v2);
//                }
//            }
//        }
        $data = Db::name('product')->where('is_on_sale=1')->select();
//        dump($data);exit;
        $this->assign('data',$data);
//        $this->assign('cate1',$cate1);
//        $cache = \think\facade\Cache::get("cate");
//        if ($cache){
//            return $cache;
//        }else{
//            $cate_data = Db::name('cate')->where('pid=0')->select();
//            \think\facade\Cache::set('cate',$cate_data);
//        }
        return $this->fetch();
    }

    public function hello($name = 'ThinkPHP5')
    {
        return 'hello,' . $name;
    }

}
