<?php
/**
 * Created by PhpStorm.
 * User: chenweihua
 * Date: 2019/11/22
 * Time: 2:57 PM
 */

namespace app\index\controller;


use think\Controller;
use think\Db;

class ShopCart extends BaseController
{
    public function initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function shopCart()
    {
        $id = input('id');
        $data = Db::name('product')->where('id',$id)->find();
        $product = [
            'uid' => '1',
            'product_id' => $id,
            'number' => '1',
            'status' => '1',
            'create_time' => time(),
        ];
        Db::name('shop_cart')->insert($product);
        $result = Db::name('shop_cart')->where('status=1')->select();
        foreach ($result as $key=>$value){
            $obj = Db::name('product')->where('id',$value['product_id'])->find();
            $result[$key]['product_name'] = $obj['product_name'];
            $result[$key]['price'] = $obj['price'];
            $result[$key]['common_price'] = $obj['common_price'];
        }
        $this->assign('result',$result);
        return $this->fetch();
    }
}