<?php
/**
 * Created by PhpStorm.
 * User: chenweihua
 * Date: 2019/11/22
 * Time: 2:57 PM
 */

namespace app\index\controller;


use think\Controller;
use think\Db;

class ShopCart extends BaseController
{
    public function initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function shopCart()
    {
        $result = Db::name('shop_cart')->where('status=1')->select();
        foreach ($result as $key=>$value){
            $obj = Db::name('product')->where('id',$value['product_id'])->find();
            $result[$key]['product_name'] = $obj['product_name'];
            $result[$key]['price'] = $obj['price'];
            $result[$key]['common_price'] = $obj['common_price'];
        }
        $result_length = count($result);
        $this->assign('result',$result);
        $this->assign('result_length',$result_length);
        return $this->fetch();
    }
}